//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.07 at 08:35:48 PM MSK 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for coordinatesDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="coordinatesDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="xCoord" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="yCoord" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "coordinatesDTO", propOrder = {
    "id",
    "xCoord",
    "yCoord"
})
public class CoordinatesDTO {

    protected int id;
    protected int xCoord;
    protected float yCoord;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the xCoord property.
     * 
     */
    public int getXCoord() {
        return xCoord;
    }

    /**
     * Sets the value of the xCoord property.
     * 
     */
    public void setXCoord(int value) {
        this.xCoord = value;
    }

    /**
     * Gets the value of the yCoord property.
     * 
     */
    public float getYCoord() {
        return yCoord;
    }

    /**
     * Sets the value of the yCoord property.
     * 
     */
    public void setYCoord(float value) {
        this.yCoord = value;
    }

}
