//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.07 at 08:35:48 PM MSK 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetVehicleRequest }
     * 
     */
    public GetVehicleRequest createGetVehicleRequest() {
        return new GetVehicleRequest();
    }

    /**
     * Create an instance of {@link AddWheelsRequest }
     * 
     */
    public AddWheelsRequest createAddWheelsRequest() {
        return new AddWheelsRequest();
    }

    /**
     * Create an instance of {@link GetVehicleResponse }
     * 
     */
    public GetVehicleResponse createGetVehicleResponse() {
        return new GetVehicleResponse();
    }

    /**
     * Create an instance of {@link VehicleDTO }
     * 
     */
    public VehicleDTO createVehicleDTO() {
        return new VehicleDTO();
    }

    /**
     * Create an instance of {@link AddWheelsResponse }
     * 
     */
    public AddWheelsResponse createAddWheelsResponse() {
        return new AddWheelsResponse();
    }

    /**
     * Create an instance of {@link CoordinatesDTO }
     * 
     */
    public CoordinatesDTO createCoordinatesDTO() {
        return new CoordinatesDTO();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

}
